kind: ConfigMap
apiVersion: v1
metadata:
  name: "ovc-{{ .Chart.Name }}-config"
  labels:
    {{- include "demo.labels" . | nindent 4 }}
data: 
    config.json: {{ .Values.configMapEnvConstant.data.environmentJson | mustToPrettyJson }}
  